spring.application.name=checkin-system
# ================== ????? ==================
spring.datasource.url=jdbc:mysql://localhost:3306/checkin_db
spring.datasource.username=root
spring.datasource.password=admin123456

# ================== MyBatis ?? ==================
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.smile.checkinsystem.entity

jwt.secret=checkin-system-secret-key-for-jwt-signature-2026
jwt.expiration=7200000



